- _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${checkpoints.checkpoints_path}
  every_n_train_steps: ${checkpoints.checkpoint_frequency}
  save_last: true
  filename: checkpoint_iter_{step}
