# @package _global_

defaults:
  - _self_
  - data: pretrain
  - model: transformer
  - module: pretrain
  - optimizer: adamw
  - scheduler: cosine
  - training: default
  - hardware: default
  - trainer: default
  - logger: default
  - eval_runner: lightning
  - eval_task: categorical_sanity
  - paths: default
  - hydra: default

task_name: eval
seed: null
ckpt_path: ???

eval:
  max_examples: 128
  prediction_mode: oracle
